version: '3'
services:
  db:
    image: 'postgres:13.0-alpine'
    ports: 
      - '${DB_PORT}:5432'
    
    environment: 
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    
    volumes:
      - 'mock_db_data:/var/lib/postgresql/data'

volumes:
  mock_db_data: {}